"use client"
import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import ScrollToTop from "./components/ScrollToTop";
import TechStack from "./components/TechStack";
import Nav from "./components/Nav";
import Intro from "./components/Intro";
import Footer from "./components/Footer";
import Background from "./components/Background";
import Projects from "./components/Projects";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio Tamlyn Springer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ScrollToTop />
      <main className="min-h-screen bg-neutral-100 px-5 sm:px-10 md:px-20 lg:px-40 xl:px-60 dark:bg-neutral-800">
        <Nav darkMode={darkMode} setDarkMode={setDarkMode} />
        <Intro darkMode={darkMode} />
        <TechStack darkMode={darkMode} />
        <Projects darkMode={darkMode} />

        <h3 className="text-4xl font-medium px-2 py-8 text-left text-green-900 dark:text-green-100">
          Background
        </h3>
        <div className="flex flex-col lg:flex-row lg:flex-wrap">
          <div>
            <Background />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
