import Head from 'next/head';
import { Inter } from '@next/font/google';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import Image from 'next/image';
import logo from '../public/logo.svg';
import logoDark from '../public/logo-d.svg';
import logoLight from '../public/logo-l.svg';
import profileDark from '../public/profile-d.png';
import profileLight from '../public/profile-l.png';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import project1 from '../public/project1.png';
import project2 from '../public/project2.png';
import project3 from '../public/project3.png';
import project4 from '../public/project4.png';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portfolio Tamlyn Springer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-h-screen bg-zinc-50 md:px-20 lg:px:40 dark:bg-zinc-900'>
        <nav className='py-4 mb-12 mx-10 flex justify-around'>
        {darkMode === true ? (
          <Image
            src={logoLight}
            alt="Light Logo"
            width={200}
            height={120}
          />
        ) : (
          <Image
            src={logoDark}
            alt="Dark Logo"
            width={200}
            height={120}
          />
        )}
          <ul className='flex items-center'>
            <li className='cursor-pointer text-2xl text-zinc-900 dark:text-zinc-200'>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} />
            </li>
            <li><a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Resume</a></li>
          </ul>
        </nav>
        <main className=''>
          <section className='flex flex-col gap-10 lg:flex-row lg:flex-wrap'>
            <div className='py-4 basis-1/3 flex-1'>
              <div className='text-center p-10 basis-1/3 flex-1'>
                <h2 className='text-5xl py-4 text-emerald-900 font-medium md:text-6xl dark:text-emerald-50'>Tamlyn Springer</h2>
                <h3 className='text-2xl py-2 md:text-3xl dark:text-emerald-100'>Software developer & designer enthusiast</h3>
                <p className='text-md py-5 leading-8 text-zinc-800 md:text-lg max-w-lg mx-auto dark:text-zinc-200'>Full-stack JavaScript developer based in Stockholm, Sweden</p>
              </div>
              <div className='text-5xl flex justify-center gap-16 py-3 text-zinc-700  dark:text-zinc-200'>
                <AiFillGithub />
                <AiFillLinkedin />
              </div>
            </div>
            <div className='relative py-4 basis-1/3 flex-1'>
            {darkMode === true ? (
              <Image
                className='mx-auto'
                src={profileDark}
                alt="Dark profile"
                width={500}
                height={500}
              />
            ) : (
              <Image
                className='mx-auto'
                src={profileLight}
                alt="Light profile"
                width={500}
                height={500}
              />
            )}
            </div>
          </section>
          <section>
            <h3 className='text-4xl font-medium py-6 text-center dark:text-emerald-100'>Projects</h3>
            <div className='flex flex-col gap-10 lg:flex-row lg:flex-wrap'>
              <article className='text-center my-10 shadow-lg rounded-xl bg-zinc-100 basis-1/3 flex-1 dark:bg-zinc-400'>
                <Image className='relative mx-auto rounded-t-xl object-cover' src={project1} alt='project-blog' width={600} height={400} />
                <h4 className='py-4 text-emerald-900 font-semibold text-2xl'>Blog</h4>
                <p className='text-gray-800 py-4'>ReactJS • Typescript • Bootstrap</p>
                <p className='text-gray-800 py-4 text-lg'><a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Site</a> <a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Code</a></p>
              </article>
              <article className='text-center my-10 shadow-lg rounded-xl bg-zinc-100 basis-1/3 flex-1 dark:bg-zinc-400'>
                <Image className='relative mx-auto rounded-t-xl' src={project2} alt='project-gallery' width={600} height={400} />
                <h4 className='py-4 text-emerald-900 font-semibold text-2xl'>Image gallery & search</h4>
                <p className='text-gray-800 py-4'>ReactJS • TailwindCSS • Unsplash API • Axios</p>
                <p className='text-gray-800 py-4 text-lg'><a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Site</a> <a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Code</a></p>
              </article>
              <article className='text-center my-10 shadow-lg rounded-xl bg-zinc-100 basis-1/3 flex-1 dark:bg-zinc-400'>
                <Image className='relative mx-auto rounded-t-xl' src={project3} alt='project-uno' width={600} height={400} />
                <h4 className='py-4 text-emerald-900 font-semibold text-2xl'>Multi-player card game</h4>
                <p className='text-gray-800 py-4'>ReactJS • SocketIO • NodeJS • Express  • Firebase</p>
                <p className='text-gray-800 py-4 text-lg'><a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Site</a> <a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Code</a> <a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Walk-through</a></p>
              </article>
              <article className=' text-center my-10 shadow-lg rounded-xl bg-zinc-100 basis-1/3 flex-1 dark:bg-zinc-400'>
                <Image className='relative mx-auto rounded-t-xl' src={project4} alt='project-blog' width={600} height={400}/>
                <h4 className='py-4 text-emerald-900 font-semibold text-2xl basis-1/3 flex-1'>Dog dating app</h4>
                <p className='text-gray-800 py-4'>HTML5 • CSS3 • Bootstrap</p>
                <p className='text-gray-800 py-4 text-lg'><a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Site</a> <a className='ml-8  bg-gradient-to-r from-emerald-900 to-emerald-600 text-white px-4 py-2 font-medium rounded' href='#'>Code</a></p>
              </article>
              </div>          
            </section>
              <div>
                <h3 className='tex-3xl py-1'>Background</h3>
                <p className='text-md py-2 leading-8 text-gray-800'></p>
              </div>
        </main>
      </div>
    </div>
  )
}
